### PR TITLE
Dependencies update (nuget for TPL Dataflow changed name)

### PR DESCRIPTION
**Pull request by tebeco**
this is probably the one required for netcoreapp2.0

https://github.com/dotnet/standard/issues/314#issuecomment-296247554

### CODE REVIEW

**Comment by tebeco** [comment]
I did not check if you updated the original source with this change or an equivalent

Do i close this one or is it still on the table ?

IIRC it was done live during the ncraft workshop

**Comment by rikace** [comment]
@tebeco thank you
the changes look good

**Comment by tebeco** [comment]
not sure what should i do with the PR and the answer to be fair ^^

**Comment by rikace** [comment]
Merged!

**Comment by tebeco** [comment]
sorry about that, i was a bit confused here trying to clean github dashboard ^^

**Comment by tebeco** [comment]
thx for the follow up

**Comment by rikace** [comment]
Thank you for the work :)
well done

**Pull request merged**
